RedHatInsights/insights-results-aggregator-cleaner

- deploy/clowdapp.yaml
Removed `dependencies` section in the clowdapp.yaml file because we don't need it
Fixes: CCXDEV-4934
> [CCXDEV-4934] removed dependencies

- README.md
- cleaner.go
- gocyclo.sh
New command line flag to display actual configuration.
Fixes #107
N/A
> Ability to show configuration

- cleaner.go
- types.go
Refactor: use `ClifFags` data type
Fixes #119
N/A
> Refactor: use `CliFlags` data type

- deploy/clowdapp.yaml
In stage env our completed cronjobs are counted into the CPU/mem quota. To not count the cronjobs into the quota, we need to use activeDeadlineSeconds for cronjobs to not count the completed jobs into quota.
The activeDeadlineSeconds stops a pod after the specified timeout if it does not complete earlier.
> [CCXDEV-7402] Fix random cpu limit on stage

- export_test.go
- storage.go
- storage_test.go
only missing function in storage.go is about initializing a database
overall percentage 26% -> 50%
Fixes 
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
> improve unit test code coverage for storage.go to 77%

- .github/workflows/golangci-lint.yml
Increase GitHub CI timeout
To be checked on CI
> Increase GitHub CI timeout

- storage.go
- storage_test.go
1. Sync with newer database schema
1. Ability to display old Advisor records
1. Ability to display old consumer errors
1. Unit tests updated as needed
```
7:57AM DBG Started
7:57AM INF DB connection configuration driverName=postgres
7:57AM INF List of old reports begin
7:57AM INF Old report age=427 cluster=5d5892d3-1f74-4ccf-91af-548dfc9767aa lastChecked=2020-04-02T09:00:05Z reported=2022-04-27T08:53:00Z
7:57AM INF Old report age=427 cluster=6d5892d3-1f74-4ccf-91af-548dfc9767aa lastChecked=2020-04-02T09:00:05Z reported=2022-04-27T08:54:36Z
7:57AM INF Old report age=427 cluster=7d5892d3-1f74-4ccf-91af-548dfc9767aa lastChecked=2020-04-02T09:00:05Z reported=2022-04-27T08:56:20Z
7:57AM INF Old report age=427 cluster=8d5892d3-1f74-4ccf-91af-548dfc9767aa lastChecked=2020-04-02T09:00:05Z …
```
> Sync with newer database schema

- README.md
Display code coverage on GitHub
N/A - will be visible on GitHub after merge
> Display code coverage on GitHub

- Dockerfile
Upgrade base image in order to use the newer version of libxml2 that is free of the mentioned CVEs
#CCXDEV-10603
N/A
> Using newer version of base image to fix CVE-2023-28484 and CVE-2023-29469

- cleaner.go
- cleaner_test.go
- config.toml
- export_test.go
- storage.go
- storage_test.go
- Ability to cleanup DVO database
- 100% unit test coverage for new code
Fixes https://issues.redhat.com/browse/CCXDEV-12163
> Ability to cleanup DVO database

- cleaner.go
- cleaner_test.go
- export_test.go
- gocyclo.sh
- storage.go
- storage_test.go
Ability to view old DVO reports on request
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
> Ability to view old DVO reports on request

- .github/workflows/bdd.yaml
- .github/workflows/gotests.yaml
- .github/workflows/linters.yaml
- Dockerfile
- build.sh
- go.mod
- Bump Go version to 1.20
- Use ubi9 as base image (already tested in other services)
CI
> Update go version to 1.20

- README.md
- cleaner.go
- cleaner_test.go
- config.go
- config_test.go
- docker-compose.yaml
- export_test.go
- storage.go
- storage_test.go
- types.go
Add target to clean up all the old records, no matter the cluster ID
Locally with a postgres DB.
> [CCXDEV-12955] Add target to clean up all the old records, no matter the cluster ID

- README.md
- docs/index.md
- export_test.go
- storage.go
- storage_test.go
Rename `dvo_report` into `dvo.dvo_report`.
Locally:
1. Run `podman-compose up -d`
2. Check the dvo-writer created the table:
```
aggregator=# SELECT * FROM dvo.dvo_report;
org_id | cluster_id | namespace_id | namespace_name | report | recommendations | objects | reported_at | last_checked_at | rule_hits_count 
--------+------------+--------------+----------------+--------+-----------------+---------+-------------+-----------------+-----------------
(0 rows)
```
3. Fill the DB with some mock data:
```
❯ ./insights-results-aggregator-cleaner -fill-in-db
{"level":"info","filename":"config","time":"2024-06-26T09:29:54+02:00","message":"parsing configuration file"}
Clowder is disabled
9:29AM DBG Started
9:29AM INF DB connection configuration …
```
> [CCXDEV-12954] Rename dvo_report into dvo.dvo_report

- deploy/clowdapp.yaml
Add a new parameter into ClowdApp to allow the definition of the maximum age of the records to be kept in the database. Records older than this age will be removed (if a real run is performed)
N/A
> Allow to specify the max age of records by parameter

- cleaner.go
- cleaner_test.go
- export_test.go
- storage.go
- storage_test.go
Ignore the schema when running `-cleanup-all` so that we don't need 2 cronjobs.
UTs
> Ignore the schema when running -cleanup-all

- storage.go
Remove orphaned `rule_hit` rows, as they can easily be kept in the database without noticing, as they don't have a timestamp-like field to filter out and they depend on org+cluster in the `report` table that might be already removed.
Tested locally with newer version of BDD, including special scenarios for this
> Remove orphan rule_hit rows

- storage.go
Running the cleaner locally might fail due to the `USING` clause depending on version of `lib/pq`
CI
> Use WHERE EXISTS instead of USING for lib/pq

- storage.go
Use `last_checked_at` to identify DVO reports' age, as `reported_at` maintains its original value even if the row was updated.
CI
> Use last_checked_at column for dvo.report table cleanup

- deploy/clowdapp.yaml
Run the cleaner once per day a 12 PM (during working hours) instead of once per hour.
Fixes CCXDEV-12953
CI
> Run the cleaner once per day at 12PM

- deploy/clowdapp.yaml
Workaround to get Konflux integration tests to run properly. RN it fails [due to missing RBAC](https://console.redhat.com/application-pipeline/workspaces/obsint-processing/applications/insights-results-aggregator-cleaner/pipelineruns/insights-results-aggregator-cleaner-68xfr-bvxlw).
CI
> Add rbac dependency in Clowdapp for Konflux PR check

- .tekton/insights-results-aggregator-cleaner-pull-request.yaml
- .tekton/insights-results-aggregator-cleaner-push.yaml
As it would take some time until the renovate would create update reference PR for this application in konflux and my workaround do not longer work in new Konflux UI i runned script provided in konflux docs https://konflux-ci.dev/docs/troubleshooting/builds/ to update konflux references. I had to update the references as the image is not build because of enterprise-contract job failing 
Fixes # (issue)
> Updating konflux .tektone references

- .tekton/insights-results-aggregator-cleaner-push.yaml
The `apply-tags` task on the Tekton configuration files needs to be updated in both on-pull-request and on-push configuration files. I missed the later, so this PR fixes this problem.
N/A
> Fix on-push job configuration
