.travis.yml, README.md, go.mod
=> Bump up Go version

README.md, cleaner.go
Ability to specify list of clusters on CLI
=>  Ability to specify list of clusters on CLI

cleaner.go
=> Fixed issues #45 and #46

cleaner.go
=> Fixed issues #43 and #44

cleaner.go
=> Fixed issues #41 and #42

cleaner.go
=> Fixed issues #37 and #38

database.go
=> Fixed issues #39 and #40

database.go
=> Fixed issues #35 and #36

cleaner.go
=> Fixed issues #33 and #34

cleaner.go
=> Fixed issues #31 and #32

cleaner.go
=> Fixed issues #29 and #30

cleaner.go
=> Fixed issues #27 and #28

.travis.yml
=> Incorporate goconst into CI

Dockerfile
this commit runs insights-results-aggregator-cleaner with haberdasher
=> [CCXDEV-3980]  add haberdasher to docker file

docs/ci.md
=> Info about CI

cleaner.go, cleaner_test.go, config.go, config_test.go, database.go, database_test.go, docs/packages/cleaner.html, docs/packages/cleaner_test.html, docs/packages/config.html, docs/packages/config_test.html, docs/packages/database.html, docs/packages/database_test.html, docs/packages/export_test.html, docs/packages/types.html, docs/packages/types_test.html, export_test.go, types.go, types_test.go
Links to generated documentation
=> Links to generated documentation

Makefile
=> Turn off Go modules

bonfire-config-devel.yaml, deploy/clowdapp.yaml
changes the app db name to deploy with clowder
Fixes # CCXDEV-4929
Can be deployed with bonfire
=> [CCXDEV-4929] changed db app name

build_deploy.sh, pr_check.sh
those files build the image in quay.io cloudservices used by clowder
Fixes CCXDEV-4924
=> [CCXDEV-4924] Add clowservices image build

pr_check.sh
=> test webhooks

config.go
=> Fixed typo

cleaner.go, config.go
Proper `file.Close()`
Fixes #92
N/A
=> Proper `file.Close()`

bdd_tests/run_tests.sh
Fixed/improved BASH script.
Fixes #99
N/A
=> Fixed issue #99

bdd_tests/run_tests.sh
=> Fixed issue #98

deploy/clowdapp.yaml
changed database name to the name of the app and added it as dependency 
Fixes CCXDEV-4934
=> fixed db name

deploy/clowdapp.yaml, pr_check.sh
changing dependency name to be compliant with the name specified in app-interface
Fixes CCXDEV-4934
=> changed dependency name

deploy/clowdapp.yaml
changed db app name
Fixes #CCXDEV-4934
=> changed db app name

Dockerfile
removes haberdasher 
Fixes CCXDEV-4934
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> removed haberdasher

docs/packages/cleaner.html, docs/packages/config.html, docs/packages/config_test.html, docs/packages/types.html
=> Updated generated doc

README.md, cleaner.go
Proper exit codes for all operations
Fixes #121
N/A
=> Proper exit codes for all operations

README.md
Add empty lines to README to test auto-deploy from master branch to STAGE env.
=> [CCXDEV-6180] test CCX auto deploy to stage env

deploy/clowdapp.yaml
add iqe plugin to clowdapp.yaml
Fixes CCXDEV-6166
check the CI pipeline, must be green
=> add iqe plugin to clowdapp.yaml

deploy/clowdapp.yaml, pr_check.sh
enable smoke tests
Fixes CCXDEV-6166
Check this pipeline, must work
=> enable smoke tests

go.mod, go.sum
Bump-up `utils` package.
Fixes #122
N/A
=> Bump-up utils package

gosec.sh, storage.go
Fixed gosec-related CI issues
To be checked on CI
=> Fixed gosec-related CI issues

.github/workflows/golangci-lint.yml, .golangci.yml, config_test.go, storage.go
=> Setup Golang CI

cleaner.go, config.go, config_test.go, storage.go, types_test.go
=> Fixed minor issues

README.md, cleaner.go, docs/packages/cleaner.html, docs/packages/config.html, docs/packages/config_test.html, docs/packages/storage.html, docs/packages/types.html, docs/packages/types_test.html, storage.go, types.go
Ability to vacuum database
Can be tested locally.
=> Ability to vacuum database

README.md, storage.go
Ability to delete from `recommendation` table
Fixes #162
N/A
=> Ability to delete from `recommendation` table

docs/index.md, docs/packages/storage_test.html
=> Updated doc

.github/workflows/golangci-lint.yml, .travis.yml, Makefile, README.md, go.mod, go.sum
Help for 'cover' and 'coverage' targets
N/A
=> Help for 'cover' and 'coverage' targets

cleaner.go, gocyclo.sh
Refactor `doSelectedOperation` + lower Go cyclo threshold
Fixes #165
Done on CI
=> Refactor `doSelectedOperation` + lower Go cyclo threshold

.travis.yml, shellcheck.sh
Shellcheck script + it ability to run on CI
Fixes #148 
Done on CI
=> Shellcheck script + it's ability to run on CI

.travis.yml
Enable Go cyclomatic complexity checks on CI
Fixes #147
Done on CI (see report)
=> Enable Go cyclomatic complexity checks on CI

CODEOWNERS, CONTRIBUTING.md, README.md
Codeowners + contributing guide + link to documentation
N/A
=> Codeowners + contributing guide + link to documentation

config.go
Don't panic if Clowder config is missing
N/A
=> Don't panic if Clowder config is missing

config_test.go
(minor) Preliminary unit test for Clowder loading
Done on CI
=> (minor) Preliminary unit test for Clowder loading

cleaner.go, cleaner_test.go, export_test.go, go.mod, go.sum
Refactoring for better testing + some unit tests
Done on CI
=> Refactoring for better testing + some unit tests

cleaner_test.go, export_test.go
Unit tests for `doSelectedOperation` function
Done on CI
=> Unit tests for `doSelectedOperation` function

docs/packages/cleaner.html, docs/packages/cleaner_test.html, docs/packages/config.html, docs/packages/config_test.html, docs/packages/export_test.html
=> Regenerated doc

README.md
=> README.md reorg

PULL_REQUEST_TEMPLATE.md
Removed items from pull request template
N/A
=> Removed items from pull request template

cleaner.go, config.go, config_test.go, export_test.go, storage.go
=> Fixed comments formatting

Makefile, README.md
Makefile target to generate function list from service executable
N/A
=> Makefile target to generate function list from service executable

types_test.go
Reformat `types_test.go`
Done on CI
=> Reformat `types_test.go`

.travis.yml
The environment variables are now set within the runner script for each service in the BDD tests repository
CI
=> Simplify BDD step in travis

go.mod, go.sum
=> Bump-up pq library

README.md
Added Go badge.
Fixes #197
N/A
=> Fixed issue #197

go.mod, go.sum
=> Bump-up toml library

cleaner.go, cleaner_test.go, config.go, config_test.go
Pass `configuration` struct via reference
Done on CI
=> Pass configuration struct via reference

cleaner.go, storage.go
Pass storage configuration by reference
To be checked on CI
=> Pass storage configuration by reference

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Issue and bug templates

cleaner_test.go, export_test.go
- Unit tests for function `readClusterListFromCLI`
- All possible cases covered
- Increased overall code coverage by 3%
Fixes #152 
=> Unit tests for function `readClusterListFromCLI`

cleaner_test.go, export_test.go
- Unit tests for function `readClusterList`
- 100% code coverage for this function
- +3% overall code coverage
Fixes #150
=> Unit tests for function `readClusterList`

config.go, config_test.go
Unit test: loading and parsing Clowder configuration
Fixes https://issues.redhat.com/browse/CCXDEV-11349
=> Unit test: loading and parsing Clowder configuration

cleaner_test.go
- Unit tests for function `PrintSummaryTable`
- 100% code coverage of this function
Fixes #154
To be performed on CI.
=> Unit tests for function `PrintSummaryTable`

.travis.yml, check_coverage.sh
=> Check code coverage on CI

cleaner_test.go, export_test.go
Unit tests for `vacuumDB` command
=> Unit tests for `vacuumDB` command

check_coverage.sh
Increase code coverage threshold to 60%
Fixes #222 
=> Increase code coverage threshold to 60%

cleaner_test.go, export_test.go, storage.go, storage_test.go
- Fix NPE in `PerformDBCleanup` function
- The fix is covered by new unit tests
Fixes https://issues.redhat.com/browse/CCXDEV-11368
To be done on CI.
=> Fix NPE in `PerformDBCleanup` function

export_test.go, storage.go, storage_test.go
- Fix NPE in `initDatabaseConnection` function
- Unit test for the new check
Fixes https://issues.redhat.com/browse/CCXDEV-11369
To be done on CI.
=> Fix NPE in `initDatabaseConnection` function

storage_test.go
- Unit tests for function/constructor `initDatabaseConnection`
- Most real cases covered
- https://issues.redhat.com/browse/CCXDEV-7827
To be tested on CI.
=> Unit tests for function/constructor `initDatabaseConnection`

check_coverage.sh
Increase code coverage threshold to 70%
=> Increase code coverage threshold to 70%

cleaner.go, cleaner_test.go, export_test.go
Fix NPE in `detectMultipleRuleDisable`
To be done on CI.
=> Fix NPE in `detectMultipleRuleDisable`

gocyclo.sh, storage.go, storage_test.go
- More unit tests for storage module
- Changed names of existing tests for better consistency
- Fix one possible NPE in the code
- Patch coverage: 100.00%
- Project coverage change: +1.61
=> More unit tests for storage module

storage_test.go
100% unit test code coverage for function `storage.performCleanupInDB`
To be tested on CI.
=> 100% unit test code coverage for function storage.performCleanupInDB

README.md
Links to generated documentation in `README.md`
N/A
=> Links to generated documentation in README.md

export_test.go, storage_test.go
- Unit tests for function `performListOfOldRatings`
- +3.86% code coverage
Fixes https://issues.redhat.com/browse/CCXDEV-11414
To be tested on CI.
=> Unit tests for function `performListOfOldRatings`

export_test.go, storage_test.go
Unit tests for function `performListOfOldConsumerErrors`
=> Unit tests for function `performListOfOldConsumerErrors`

storage_test.go
- Finished unit tests for storage
- All functions are covered
- Coverage for this module is 91.5%
- Every function has coverage at least 87.5%
=> Finished unit tests for storage

cleaner.go, cleaner_test.go, export_test.go
Unit tests for `fillIDatabase` function
- Fixes https://issues.redhat.com/browse/CCXDEV-11412
- 100% code coverage for this function
- Fixes possible NPE
- Overall code coverage exceeds 80%
=> Unit tests for `fillInDatabase` function

cleaner_test.go
- Unit tests for `cleanup` function
- 100% code coverage for tested function
- Over 83% total code coverage
Fixes https://issues.redhat.com/browse/CCXDEV-11410
=> Unit tests for `cleanup` function

cleaner_test.go
- Unit tests for `doSelectedOperationFunction`
- 100% code coverage with all cases tested
Fixes https://issues.redhat.com/browse/CCXDEV-11474
=> Unit tests for `doSelectedOperationFunction`

cleaner_test.go, export_test.go
- Unit tests for `displayOldRecordsFunction`
- 100% code coverage for tested function
Fixes https://issues.redhat.com/browse/CCXDEV-11413
=> Unit tests for `displayOldRecordsFunction`

cleaner_test.go, export_test.go
- Unit tests for function `detectMultipleRuleDisable`
- 100% code coverage for tested function
- overall code coverage exceeds 86%
Fixes https://issues.redhat.com/browse/CCXDEV-11411
To be done on CI.
=> Unit tests for function `detectMultipleRuleDisable`

check_coverage.sh
Bump-up code coverage threshold to 80%
=> Bump-up code coverage threshold to 80%

.github/workflows/golangci-lint.yml, cleaner_test.go, config_test.go, storage.go, storage_test.go
=> More linters on CI

Dockerfile
Bump-up Go toolset in Dockerfile
To be checked elsewhere.
=> Bump-up Go toolset in Dockerfile

README.md, cleaner.go, config.go, config.toml, config_test.go, deploy/clowdapp.yaml, docs/index.md, tests/config1.toml, tests/config2.toml
- Added new configuration option: (db)schema
- Updated documentation accordingly
- Updated deployment accordingly (now it's set to fixed value!)
- Configuration checking code
- Unit tests for the new code
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> Db schema configuration option

cleaner.go, cleaner_test.go, storage.go, storage_test.go
- Fill in DVO database functionality
- Does not affect existing DB schema(s)
- Unit tests added to cover new code
=> Fill in DVO database functionality

storage_test.go
Refactoring: import main module just once
=> Refactoring: import main module just once

Dockerfile, pr_check.sh
Updated builder image and base image to ubi9 based ones.
Fixes #[CCXDEV-11999](https://issues.redhat.com/browse/CCXDEV-11999)
Build tested locally
=> Update build and base image to ubi9 based ones

.github/workflows/linters.yaml
Splitting linters jobs to be more readable.
Fixes # https://issues.redhat.com/browse/CCXDEV-12634
=> Splitting CI jobs

cleaner_test.go, storage.go, storage_test.go
Exit the program if there is any error deleting a row so that we can check, fix it and prevent the rest of the tables to be affected.
Unit tests.
=> [CCXDEV-12989] Exit if there is any error deleting a table

deploy/clowdapp.yaml
Adding a parameter into the Clowder template to control the way of executing the aggregator cleaner
N/A
=> Add parameter for controling the execution of the cleaner

deploy/clowdapp.yaml
The clowdapp definition contains a repeated `resources` section. 
N/A
=> Remove duplicated resources section in clowdapp deployment file

storage.go
Reorder the delete clauses.
Fixes # (issue)
N/A
=> Reorder delete clauses to avoid misleading results when deleting

storage.go
The query with the `OR` clause is way slower than expected. Let's try improving its performance.
CI
=> Refactor deleteOldOCPRuleHits to use prepared table instead of subqueries

Dockerfile
Use an image from registry.access.redhat.com for Konflux
Fixes CCXDEV-13026 partially
CI
=> Update image used for building container

.github/workflows/bots-automerge.yml
[CCXDEV-14404] Use Github-Actions to approve/automerge konflux PRs
=> [CCXDEV-14404] Use Github-Actions to approve/automerge konflux PRs

goerrcheck.sh, ineffassign.sh
Linters fixed
Fixes # (issue)
CI
=> Fixing Go linters tests

.github/workflows/bots-automerge.yml
[CCXDEV-14176] GH actions: add konflux PR automerging
=> [CCXDEV-14176] GH actions: add konflux PR automerging

.github/workflows/gotests.yaml, pr_check.sh
The codecov.io is out of date because we are no longer pushing the coverage there.
This CI.
=> [CCXDEV-15082] fix codecov.io
